### ISSUE TITLE
Farben CI/CD MunichWays

### ISSUE THREAD

**Issue by thomas-munichways** [AppWerft/MunichWays#1]
hier noch unsere MunichWays Farben. Wir hätten gern unser freundiches Orange für die roten Strecken

grün:  #27b403
gelb: #fbba00
rot: orange: #ff6600
schwarz: #000000

andere generelle Farben MunichWays CI:
blau: #6699cc
grau: #9c9d9f 

Alle Farbwerte: https://drive.google.com/file/d/1Mt7Da6fZSWj7zc_gspL0ZUSa955YQR6f/view?usp=sharing

**Comment by AppWerft** [comment]
eingebaut.

**Comment by AppWerft** [comment]
Routen, die keine Farben haben, sind blau dargestellt.

**Comment by thomas-munichways** [comment]
prima, passt
