### ISSUE TITLE
Link Webseite

### ISSUE THREAD

**Issue by thomas-munichways** [AppWerft/MunichWays#10]
direkt auf die Unterseite RadlVorrangNetz:
https://www.munichways.com/radlvorrangnetz/

**Comment by NachiketaVadera** [comment]
I'll submit a PR regarding that.

**Comment by AppWerft** [comment]
meinst Du damit die angezeigt Webseite? Übrigens friert die App beim Aufruf der Seite ein, weil die zu ungünstig und ressourcenhungrig gebaut ist

**Comment by AppWerft** [comment]
Es sind 134 Request und 3,98 MB. Eventuell kannst Du die JS und CSS Dateien zusammenfassen.
Schau mal meine Seite, kommt viel schneller:
https://openscience.hamburg.de/de/suchen-entdecken/suchergebnis/
