### ISSUE TITLE
Farberklärung mit Link zur ausführlichen Erklärung

### ISSUE THREAD

**Issue by thomas-munichways** [AppWerft/MunichWays#11]
Unter der Beschreibung der Farben folgenden Link ergänzen:

"Ausführliche Bewertungskriterien"
https://www.munichways.com/radlvorrangnetz/berwertungskriterien-radwege/

**Comment by AppWerft** [comment]
Wie schon erwähnt würde ich Links in die Webwelt tunlichst vermeiden.
