### ISSUE TITLE
Menü: ÖPNV und Hauptrouten LHM raus

### ISSUE THREAD

**Issue by thomas-munichways** [AppWerft/MunichWays#2]
ÖPNV: wird unübersichtlich und brauchen wir nicht. Nett wären die großen Haltestellen ( Bahn/S-Bahn/U-Bahn) als Orientierung aber nur wenn es dezent auf der Karte dargestellt wird.

Hauptrouten LHM sind nicht mehr aktuell und möchten wir nicht in der App anzeigen.

**Comment by AppWerft** [comment]
Klar, Behördendaten.
hast Du die geodaten der Stationen?
