### ISSUE TITLE
MunichWays Logo als Ladebild anzeigen

### ISSUE THREAD

**Issue by thomas-munichways** [AppWerft/MunichWays#4]
Beim laden der App wird ein Sternenbild angezeigt.
Stattdessen soll das Logo von Munichways gezeigt werden

**Comment by AppWerft** [comment]
Bitte in genüpgend großer Auflösung zur Verfügung stellen

**Comment by thomas-munichways** [comment]
https://drive.google.com/file/d/1iXiex2nHy9Yu1gcQgOO5D27zzUtC8NbS/view?usp=sharing

**Comment by AppWerft** [comment]
Danke
