### ISSUE TITLE
Text Popup

### ISSUE THREAD

**Issue by thomas-munichways** [AppWerft/MunichWays#5]
Das Feld <Description> aus dem Carto dataset mach Probleme.
 html für Links oder Bilder werden nicht richtig angezeigt. Diese Zusatzinfos sind nicht notwendig.
Prio:
1. Name
2. Strecke
3. Ist
der Rest ist nice to have
ggf.
4. Kategorie
5. Links

**Comment by AppWerft** [comment]
Es gibt einen kürzeren Titel und einen längeren Untertitel HTML ist nicht möglich.

**Comment by thomas-munichways** [comment]
OK, dann vielleicht Name als Titel und 2-3 oder 2-5 als Untertitel

wenn ich mehrer Strecken nacheinander anklicke, wird immer der gleiche Text, also der der ersten Strecke, angezeigt.

**Comment by AppWerft** [comment]
was sind as für Ziffern?

**Comment by thomas-munichways** [comment]
Titel: Name
Text: Strecke und Ist

**Comment by AppWerft** [comment]
Was ist Strecke?
{"cartodb_id":364,"name":"Unterführung Domagstr ","description":null,"netztyp":"3_Gesamt","munichways_id":null,"ist":null,"soll":null,"kategorie":null,"farbe":"grün","links":null,"strecke":null}

**Comment by AppWerft** [comment]
Habe jetzt Description + Ist
