### ISSUE TITLE
User Story: Orientierung an markanten Orte der Stadt

### ISSUE THREAD

**Issue by thomas-munichways** [AppWerft/MunichWays#7]
Ich als User möchte zwar hauptsächlich die bewerteten Strecken sehen aber zur Orientierung möchte ich die markanten Orte der Stadt gut erkennen können. Beispiele sind:
Nymphenburg Park, Isar, Perlcher Forst, Theresienwiese, Bahngleise, Hauptbahnhof, große Friedhöfe, Auto-Hauptstraßen

**Comment by AppWerft** [comment]
Was soll ich machen?

**Comment by thomas-munichways** [comment]
Sehr gut gelöst durch die neuen Kartenstiele.
Stiel 1, mit mehr grün bei den Parks und blau für die Isar gefällt mir am besten.
Das sollte die Standardkarte werden.
